### PR TITLE
Update angular and dependencies to latest versions

### PR DESCRIPTION
**Pull request by andrbo**
- Update to latest version of angular (16.2.*)
- Update dependencies and dev dependencies to latest available versions

- Small refactor of ipAddressValidator used by crawlhostgroupconfig component to support changes in latest version of ip-address(v9.0.5)

### CODE REVIEW

**Comment by trym-b** [comment]
It looks like the CI failed with this error:
```
✔ Browser application bundle generation complete.

./src/styles/theme.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
4 │ @use '@material/textfield' as mdc-textfield;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@angular/material/form-field/_form-field-density.scss 4:1     @use
  node_modules/@angular/material/paginator/_paginator-theme.scss 7:1         @use
  node_modules/@angular/material/core/density/private/_all-density.scss 9:1  @forward
  @angular/_index.scss 20:1                                                  @use
  src/styles/theme.scss 1:1                                                  root stylesheet

./src/styles/theme.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Can't find stylesheet to import.
  ╷
4 │ @use '@material/textfield' as mdc-textfield;
  │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/@angular/material/form-field/_form-field-density.scss 4:1     @use
  node_modules/@angular/material/paginator/_paginator-theme.scss 7:1         @use
  node_modules/@angular/material/core/density/private/_all-density.scss 9:1  @forward
  @angular/_index.scss 20:1                                                  @use
  src/styles/theme.scss 1:1                                                  root stylesheet


31 10 2023 16:58:33.112:INFO [karma-server]: Karma v6.4.2 server started at http://localhost:9876/
31 10 2023 16:58:33.123:INFO [launcher]: Launching browsers ChromeHeadless with concurrency 1
31 10 2023 16:58:33.124:ERROR [karma-server]: Error: Found 1 load error
    at Server.<anonymous> (/home/runner/work/veidemann-dashboard/veidemann-dashboard/node_modules/karma/lib/server.js:243:26)
    at Object.onceWrapper (node:events:631:28)
    at Server.emit (node:events:529:35)
    at Server.emit (node:domain:489:12)
    at emitListeningNT (node:net:1851:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
✔ Browser application bundle generation complete.
✔ Browser application bundle generation complete.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

It is not quite clear what went wrong here, as I am not familiar with this project. It does seem to be missing some resources though.

**Comment by andrbo** [comment]
Since the test worked locally I tried to rerun the CI jobs, and now they passed. 
Could there be some caching issues or something with the CI?

**Comment by trym-b** [comment]
> Since the test worked locally I tried to rerun the CI jobs, and now they passed. Could there be some caching issues or something with the CI?

That could very much be the case, but in case the build now is flaky, could you perhaps try to run the build a few times to see if the error was just a one-time phenomenon?

**Comment by andrbo** [comment]
Tried it a couple more times, and it still passes all checks. 3/4 successful runs where only the first one experienced  the issue.

**Review by trym-b — COMMENTED** [review]
The first commit seems fine, but add a bit more to the descriptions of each commit message? This will make it easier to review changes at a later point in time, by running `git log` or similar tools

**Review by trym-b — APPROVED** [review]
Had an IRL review together, and we decided to merge the commits together since they are not standalone changes (they are both required to build). And put the PR description into the commit message for posteriority.

**Pull request merged**
